name: dart_ecommerce
description: A simple Dart console application with Riverpod for e-commerce.
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  riverpod: ^2.0.0
  collection: ^1.17.0

dev_dependencies:
  build_runner: ^2.1.8
  riverpod_generator: ^2.0.0
  lints: ^4.0.0
  test: ^1.24.0
